
Book.create(:title =>"Las mil y una noches", :author=>"Anonimo")
Book.create(:title =>"La historia de Genji", :author=>"Murasaki Shikibu")
Book.create(:title =>"Cantar del Mio Cid", :author=>"Anonimo")
Book.create(:title =>"Libro de Buen Amor", :author=>"Juan Ruiz")
Book.create(:title =>"El conde Lucanor", :author=>"Don Juan Manuel")
Book.create(:title =>"Metamorfosis, o El asno de oro", :author=>"Lucio Apuleyo")
Book.create(:title =>"Tirant lo Blanc", :author=>"Joanot Martorell")
Book.create(:title =>"La Celestina", :author=>"Fernando de Rojas")
Book.create(:title =>"Amadis de Gaula", :author=>"Garci Rodriguez de Montalvo")
Book.create(:title =>"Lazarillo de Tormes", :author=>"Anonimo")
Book.create(:title =>"Gargatua y Pantagruel", :author=>"Francois Rabelais")
Book.create(:title =>"Los Lusiadas", :author=>"Luis Vaz de Camoes")
Book.create(:title =>"Libro de la vida", :author=>"Teresa de Jesus")
Book.create(:title =>"Guzman de Alfarache", :author=>"Mateo Aleman")
Book.create(:title =>"Novelas ejemplares", :author=>"Miguel de Cervantes Saavedra")
Book.create(:title =>"Don Quijote de la Mancha", :author=>"Miguel de Cervantes Saavedra")
Book.create(:title =>"Los trabajos de Persiles y Segismunda", :author=>"Miguel de Cervantes Saavedra")
Book.create(:title =>"El buscon", :author=>"Francisco de Quevedo")
Book.create(:title =>"Historia verdadera de la conquista de la Nueva Espana", :author=>"Bernal Diaz del Castillo")
Book.create(:title =>"La Dorotea", :author=>"Lope de Vega")
Book.create(:title =>"El Criticon", :author=>"Baltasar Gracian")
Book.create(:title =>"La princesa de Cleves", :author=>"Marie-Madelaine Pioche de Lavergne, condesa de La Fayette")
Book.create(:title =>"Robinson Crusoe", :author=>"Daniel Defoe")
Book.create(:title =>"Love in Excess", :author=>"Eliza Haywood")
Book.create(:title =>"Moll Flanders", :author=>"Daniel Defoe")
Book.create(:title =>"Los viajes de Gulliver", :author=>"Jonathan Swift")
Book.create(:title =>"Una modesta proposicion", :author=>"Jonathan Swift")
Book.create(:title =>"Joseph Andrews", :author=>"Henry Fielding")
Book.create(:title =>"Memoirs of Martinus Scriblerus", :author=>"J. Arbuthnot, J. Gay, T. Parnell, A. Pope, J. Swift")
Book.create(:title =>"Pamela", :author=>"Samuel Richardson")
Book.create(:title =>"Clarissa", :author=>"Samuel Richardson")
Book.create(:title =>"Tom Jones", :author=>"Henry Fielding")
Book.create(:title =>"Fanny Hill: Memorias de una cortesana", :author=>"John Cleland")
Book.create(:title =>"Peregrine Pickle", :author=>"Tobias George Smollett")
Book.create(:title =>"Candido, o el optimismo", :author=>"Voltaire")
Book.create(:title =>"La historia de Rasselas, principe de Abisinia", :author=>"Samuel Johnson")
Book.create(:title =>"Julia, o la nueva Eloisa", :author=>"Jean-Jacques Rousseau")
Book.create(:title =>"Emilio, o de la educacion", :author=>"Jean-Jacques Rousseau")
Book.create(:title =>"El castillo de Otranto", :author=>"Horace Walpole")
Book.create(:title =>"El vicario de Wakefield", :author=>"Oliver Goldsmith")
Book.create(:title =>"Tristram Shandy", :author=>"Laurence Sterne")
Book.create(:title =>"Viaje sentimental por Francia e Italia", :author=>"Laurence Sterne")
Book.create(:title =>"The man of feeling", :author=>"Henry Mackenzie")
Book.create(:title =>"Humphry Clinker", :author=>"Tobias George Smollett")
Book.create(:title =>"Las desventuras del joven Werther", :author=>"Johann Wolfgang von Goethe")
Book.create(:title =>"Evelina", :author=>"Fanny Burney")
Book.create(:title =>"Las ensonaciones del paseante solitario", :author=>"Jean-Jacques Rousseau")
Book.create(:title =>"Las amistades peligrosas", :author=>"Pierre Choderlos de Laclos")
Book.create(:title =>"Las confesiones", :author=>"Jean-Jacques Rousseau")
Book.create(:title =>"Las ciento veinte jornadas de Sodoma", :author=>"Marques de Sade")
Book.create(:title =>"Anton Reiser", :author=>"Karl Philipp Moritz")
Book.create(:title =>"Vathez", :author=>"William Beckford")
Book.create(:title =>"Justine", :author=>"Marques de Sade")
Book.create(:title =>"Sueno en el pabellon rojo", :author=>"Cao Xueqin")
Book.create(:title =>"Las aventuras de Caleb Williams", :author=>"William Godwin")
Book.create(:title =>"Narracion de la vida de Olaudah Equiano", :author=>"Olaudah Equiano")
Book.create(:title =>"Los misterios de Udolfo", :author=>"Ann Radcliffe")
Book.create(:title =>"Los anos de aprendizaje de Wilhelm Meister", :author=>"Johann Wolfgang von Goethe")
Book.create(:title =>"El monje", :author=>"M.G. Lewis")
Book.create(:title =>"Camila", :author=>"Fanny Burney")
Book.create(:title =>"Jacques el fatalista", :author=>"Denis Diderot")
Book.create(:title =>"La religiosa", :author=>"Denis Diderot")
Book.create(:title =>"Hiperion", :author=>"Friedrich Holderlin")
Book.create(:title =>"El castillo de Rackrent", :author=>"Maria Edgeworth")
Book.create(:title =>"Enrique de Ofterdingen", :author=>"Novalis")
Book.create(:title =>"El sobrino de Rameau", :author=>"Denis Diderot")
Book.create(:title =>"Las afinidades electivas", :author=>"Johann Wolfgang von Goethe")
Book.create(:title =>"Michael Kohlhaas", :author=>"Heinrich von Kleist")
Book.create(:title =>"Sentido y sensibilidad", :author=>"Jane Austen")
Book.create(:title =>"Orgullo y prejuicio", :author=>"Jane Austen")
Book.create(:title =>"Mansfield Park", :author=>"Jane Austen")
Book.create(:title =>"Emma", :author=>"Jane Austen")
Book.create(:title =>"Rob Roy", :author=>"Sir Walter Scott")
Book.create(:title =>"Frankenstein", :author=>"Mary Wollstonecraft Shelley")
Book.create(:title =>"Ivanhoe", :author=>"Sir Walter Scott")
Book.create(:title =>"Melmoth El Errabundo", :author=>"Charles Robert Maturin")
Book.create(:title =>"Opiniones del gato Murr", :author=>"Hoffmann")
Book.create(:title =>"Memorias privadas y confesiones de un pecador justificado", :author=>"James Hogg")
Book.create(:title =>"De la vida de un inutil", :author=>"Joseph von Eichendorff")
Book.create(:title =>"El ultimo mohicano", :author=>"James Fenimore Cooper")
Book.create(:title =>"Los novios", :author=>"Alessandro Manzoni")
Book.create(:title =>"Rojo y negro", :author=>"Stendhal")
Book.create(:title =>"El jorobado de Notre Dame", :author=>"Victor Hugo")
Book.create(:title =>"Eugenio Oneguin", :author=>"Alexandr Pushkin")
Book.create(:title =>"Eugenia Grandet", :author=>"Honore de Balzac")
Book.create(:title =>"Papa Goriot", :author=>"Honore de Balzac")
Book.create(:title =>"La nariz", :author=>"Nicolai Gogol")
Book.create(:title =>"Oliver Twist", :author=>"Charles Dickens")
Book.create(:title =>"El leon de Flandes", :author=>"Hendrik Conscience")
Book.create(:title =>"La cartuja de Parma", :author=>"Stendhal")
Book.create(:title =>"La caida de la casa Usher", :author=>"Edgar Allan Poe")
Book.create(:title =>"Camera Obscura", :author=>"Hilderbrand")
Book.create(:title =>"Un heroe de nuestro tiempo", :author=>"Mijail I. Lermontov")
Book.create(:title =>"Almas muertas", :author=>"Nicolai Gogol")
Book.create(:title =>"Las ilusiones perdidas", :author=>"Honore de Balzac")
Book.create(:title =>"El pozo y el pendulo", :author=>"Edgar Allan Poe")
Book.create(:title =>"Los tres mosqueteros", :author=>"Alejandro Dumas")
Book.create(:title =>"Facundo", :author=>"Domingo Faustino Sarmiento")
Book.create(:title =>"La charca del diablo", :author=>"Georges Sand")
Book.create(:title =>"El conde de Montecristo", :author=>"Alejandro Dumas")
Book.create(:title =>"Jane Eyre", :author=>"Charlotte Bronte")
Book.create(:title =>"La feria de las vanidades", :author=>"William Makepeace Thackeray")
Book.create(:title =>"Cumbres borrascosas", :author=>"Emily Bronte")
Book.create(:title =>"La inquilina de Wildfell Hall", :author=>"Anne Bronte")
Book.create(:title =>"David Copperfield", :author=>"Charles Dickens")
Book.create(:title =>"La letra escarlata", :author=>"Nathaniel Hawthorne")
Book.create(:title =>"Moby Dick", :author=>"Herman Melville")
Book.create(:title =>"La casa de las siete torres", :author=>"Nathaniel Hawthorne")
Book.create(:title =>"La cabana del Tio Tom", :author=>"Harriet Beecher Stowe")
Book.create(:title =>"Cranford", :author=>"Elizabeth Gaskell")
Book.create(:title =>"La casa desolada", :author=>"Charles Dickens")
Book.create(:title =>"Walden", :author=>"Henry David Thoreau")
Book.create(:title =>"Enrique el verde", :author=>"Gottfried Keller")
Book.create(:title =>"Norte y sur", :author=>"Elizabeth Gaskell")
Book.create(:title =>"Madame Bovary", :author=>"Gustave Flaubert")
Book.create(:title =>"Der Nachsommer", :author=>"Adalbert Stifter")
Book.create(:title =>"Adam Bede", :author=>"George Eliot")
Book.create(:title =>"Oblomov", :author=>"Ivan Goncharov")
Book.create(:title =>"La mujer de blanco", :author=>"Wilkie Collins")
Book.create(:title =>"El molino de Floss", :author=>"George Eliot")
Book.create(:title =>"Max Havelaar", :author=>"Multatuli")
Book.create(:title =>"Grandes esperanzas", :author=>"Charles Dickens")
Book.create(:title =>"Silas Marner", :author=>"George Eliot")
Book.create(:title =>"Padres e hijos", :author=>"Ivan Turgueniev")
Book.create(:title =>"Los miserables", :author=>"Victor Hugo")
Book.create(:title =>"Los ninos del agua", :author=>"Charles Kingsley")
Book.create(:title =>"Memorias del subsuelo", :author=>"Fiodor Dostoievski")
Book.create(:title =>"El tio Silas", :author=>"Sheridan Le Fanu")
Book.create(:title =>"Alicia en el Pais de las Maravillas", :author=>"Lewis Carroll")
Book.create(:title =>"Viaje al centro de la Tierra", :author=>"Jules Verne")
Book.create(:title =>"Crimen y castigo", :author=>"Fiodor Dostoievski")
Book.create(:title =>"Maria", :author=>"Jorge Isaacs")
Book.create(:title =>"Teresa Raquin", :author=>"Emile Zola")
Book.create(:title =>"La piedra lunar", :author=>"Wilkie Collins")
Book.create(:title =>"Mujercitas", :author=>"Louisa May Alcott")
Book.create(:title =>"El idiota", :author=>"Fiodor Dostoievski")
Book.create(:title =>"Los cantos de Maldonor", :author=>"Conde de Lautreamont")
Book.create(:title =>"Phineas Finn", :author=>"Anthony Trollope")
Book.create(:title =>"La educacion sentimental", :author=>"Gustave Flaubert")
Book.create(:title =>"Guerra y paz", :author=>"Lev Tolstoi")
Book.create(:title =>"Leyendas", :author=>"Gustavo Adolfo Becquer")
Book.create(:title =>"Alicia a traves del espejo", :author=>"Lewis Carroll")
Book.create(:title =>"Middlemarch", :author=>"George Eliot")
Book.create(:title =>"Aguas primaverales", :author=>"Ivan Turgueniev")
Book.create(:title =>"Erewhon", :author=>"Samuel Butler")
Book.create(:title =>"Los demonios", :author=>"Fiodor Dostoievski")
Book.create(:title =>"Las criaturas del espejo", :author=>"Sheridan Le Fanu")
Book.create(:title =>"La vuelta al mundo en 80 dias", :author=>"Jules Verne")
Book.create(:title =>"Episodios nacionales", :author=>"Benito Perez Galdos")
Book.create(:title =>"Lejos del mundanal ruido", :author=>"Thomas Hardy")
Book.create(:title =>"Pepita Jimenez", :author=>"Juan Valera")
Book.create(:title =>"El crimen del padre Amaro", :author=>"Jose Maria Eca de Queiros")
Book.create(:title =>"La taberna", :author=>"Emile Zola")
Book.create(:title =>"Ana Karenina", :author=>"Lev Tolstoi")
Book.create(:title =>"Martin Fierro", :author=>"Jose Hernandez")
Book.create(:title =>"La habitacion roja", :author=>"August Strindberg")
Book.create(:title =>"Ben-Hur", :author=>"Lew Wallace")
Book.create(:title =>"Nana", :author=>"Emile Zola")
Book.create(:title =>"Retrato de una dama", :author=>"Henry James")
Book.create(:title =>"Los Malavoglia", :author=>"Giovanni Verga")
Book.create(:title =>"Memorias postumas de Bras Cubas", :author=>"Joaquim Maria Machado de Assis")
Book.create(:title =>"El amigo manso", :author=>"Benito Perez Galdos")
Book.create(:title =>"La isla del tesoro", :author=>"Robert Louis Stevenson")
Book.create(:title =>"Una vida", :author=>"Guy de Maupassant")
Book.create(:title =>"La muerte de Ivan Ilich", :author=>"Lev Tolstoi")
Book.create(:title =>"A contrapelo", :author=>"Joris-Karl Huysmans")
Book.create(:title =>"Mario el epicureo", :author=>"Walter Pater")
Book.create(:title =>"Bel-Ami", :author=>"Guy de Maupassant")
Book.create(:title =>"La regenta", :author=>"Leopoldo Alas, Clarin")
Book.create(:title =>"Las aventuras de Huckleberry Finn", :author=>"Mark Twain")
Book.create(:title =>"Germinal", :author=>"Emile Zola")
Book.create(:title =>"Sotileza", :author=>"Jose Maria de Pereda")
Book.create(:title =>"Fortunata y Jacinta", :author=>"Benito Perez Galdos")
Book.create(:title =>"El extrano caso del Dr. Jeckyll y Mr. Hyde", :author=>"Robert Louis Stevenson")
Book.create(:title =>"Los pazos de Ulloa", :author=>"Emilia Pardo Bazan")
Book.create(:title =>"Los habitantes de Hemso", :author=>"August Strindberg")
Book.create(:title =>"Pierre y Jean", :author=>"Guy de Maupassant")
Book.create(:title =>"Bajo el yugo", :author=>"Ivan Vazov")
Book.create(:title =>"El placer", :author=>"Gabriele D'Annunzio")
Book.create(:title =>"Eline Vere", :author=>"Louis Couperus")
Book.create(:title =>"Hambre", :author=>"Knut Hamsun")
Book.create(:title =>"La febre d'or", :author=>"Narcis Oller")
Book.create(:title =>"La bestia humana", :author=>"Emile Zola")
Book.create(:title =>"Thais, la cortesana", :author=>"Anatole France")
Book.create(:title =>"La sonata a Kreutzer", :author=>"Lev Tolstoi")
Book.create(:title =>"El retrato de Dorian Gray", :author=>"Oscar Wilde")
Book.create(:title =>"Alla abajo", :author=>"Joris-Karl Huysmans")
Book.create(:title =>"Tess, la de los d'Uberville", :author=>"Thomas Hardy")
Book.create(:title =>"La saga de Gosta Berling", :author=>"Selma Lagerlof")
Book.create(:title =>"New Grub Street", :author=>"George Gissing")
Book.create(:title =>"Noticias de ninguna parte", :author=>"William Morris")
Book.create(:title =>"Las aventuras de Sherlock Holmes", :author=>"Arthun Conan Doyle")
Book.create(:title =>"Diario de un don nadie", :author=>"George & Weedon Grossmith")
Book.create(:title =>"Dona Berta. Cuervo. Supercheria", :author=>"Leopoldo Alas")
Book.create(:title =>"Jude el oscuro", :author=>"Thomas Hardy")
Book.create(:title =>"Effi Briest", :author=>"Theodor Fontane")
Book.create(:title =>"La maquina del tiempo", :author=>"H. G. Wells")
Book.create(:title =>"La isla del Dr. Moreau", :author=>"H. G. Wells")
Book.create(:title =>"Quo Vadis", :author=>"Henryk Sienkiewicz")
Book.create(:title =>"Dracula", :author=>"Bram Stoker")
Book.create(:title =>"Lo que Maisie sabia", :author=>"Henry James")
Book.create(:title =>"Misericordia", :author=>"Benito Perez Galdos")
Book.create(:title =>"Faraon", :author=>"Boleslaw Prus")
Book.create(:title =>"Los alimentos terrenales", :author=>"Andre Gide")
Book.create(:title =>"La guerra de los mundos", :author=>"H. G. Wells")
Book.create(:title =>"Senectud", :author=>"Italo Svevo")
Book.create(:title =>"Don Casmurro", :author=>"Joachim Maria Machado de Assis")
Book.create(:title =>"El despertar", :author=>"Kate Chopin")
Book.create(:title =>"El Stechlin", :author=>"Theodor Fontane")
Book.create(:title =>"Las estrellas de Eger", :author=>"Geza Gardonyi")
Book.create(:title =>"Some Experiences of an Irish R. M.", :author=>"E. Somerville y V. M. Ross")
Book.create(:title =>"Los tigres de Mompracem", :author=>"Emilio Salgari")
Book.create(:title =>"Nuestra Carrie", :author=>"Theodore Dreiser")
Book.create(:title =>"El teniente Gustl", :author=>"Arthur Schnitzler")
Book.create(:title =>"Kim", :author=>"Rudyard Kipling")
Book.create(:title =>"Los Buddenbrook", :author=>"Thomas Mann")
Book.create(:title =>"El sabueso de los Baskerville", :author=>"Arthur Conan Doyle")
Book.create(:title =>"El corazon de las tinieblas", :author=>"Joseph Conrad")
Book.create(:title =>"Canas y barro", :author=>"Vicente Blasco Ibanez")
Book.create(:title =>"El inmoralista", :author=>"Andre Gide")
Book.create(:title =>"Los embajadores", :author=>"Henry James")
Book.create(:title =>"El enigma de las arenas", :author=>"Erskine Childers")
Book.create(:title =>"La llamada de la selva", :author=>"Jack London")
Book.create(:title =>"Sucesos memorables de un enfermo de los nervios", :author=>"Daniel P. Shreber")
Book.create(:title =>"Sonatas", :author=>"Ramon Maria del Valle-Inclan")
Book.create(:title =>"Adriano VII", :author=>"Frederick Rolfe")
Book.create(:title =>"Nostromo", :author=>"Joseph Conrad")
Book.create(:title =>"La casa de la alegria", :author=>"Edith Wharton")
Book.create(:title =>"El profesor Unrat", :author=>"Heinrich Mann")
Book.create(:title =>"Solitud", :author=>"Victor Catala")
Book.create(:title =>"Los extravios del colegial Torless", :author=>"Robert Musil")
Book.create(:title =>"La saga de los Forsyte", :author=>"John Galsworthy")
Book.create(:title =>"La jungla", :author=>"Upton Sinclair")
Book.create(:title =>"El agente secreto", :author=>"Joseph Conrad")
Book.create(:title =>"La madre", :author=>"Maximo Gorki")
Book.create(:title =>"La casa en el confin de la tierra", :author=>"William Hope Hodgson")
Book.create(:title =>"Cuento de viejas", :author=>"Arnold Bennett")
Book.create(:title =>"El infierno", :author=>"Henri Barbusse")
Book.create(:title =>"Una habitacion con vistas", :author=>"E. M. Forster")
Book.create(:title =>"La puerta estrecha", :author=>"Andre Gide")
Book.create(:title =>"Los cuadernos de Malte Laurids Brigge", :author=>"Rainer Maria Rilke")
Book.create(:title =>"Regreso a Howards End", :author=>"E M. Forster")
Book.create(:title =>"Impresiones de Africa", :author=>"Raymond Roussel")
Book.create(:title =>"El arbol de la ciencia", :author=>"Pio Baroja")
Book.create(:title =>"Ethan Frome", :author=>"Edith Wharton")
Book.create(:title =>"Castilla", :author=>"Azorin")
Book.create(:title =>"The Charwoman's Daughter", :author=>"James Stephens")
Book.create(:title =>"La muerte en Venecia", :author=>"Thomas Mann")
Book.create(:title =>"Hijos y amantes", :author=>"D. H. Lawrence")
Book.create(:title =>"Memorias de un hombre de accion", :author=>"Pio Baroja")
Book.create(:title =>"Platero y yo", :author=>"Juan Ramon Jimenez")
Book.create(:title =>"Niebla", :author=>"Miguel de Unamuno")
Book.create(:title =>"Kokoro", :author=>"Natsume Soseki")
Book.create(:title =>"Los treinta y nueve escalones", :author=>"John Buchan")
Book.create(:title =>"El arco iris", :author=>"D. H. Lawrence")
Book.create(:title =>"Servidumbre humana", :author=>"William Somerset Maugham")
Book.create(:title =>"El buen soldado", :author=>"Ford Madox Ford")
Book.create(:title =>"Rashomon y otros cuentos", :author=>"Akutagawa Ryunosuke")
Book.create(:title =>"El fuego", :author=>"Henri Barbusse")
Book.create(:title =>"Retrato del artista adolescente", :author=>"James Joyce")
Book.create(:title =>"Los de abajo", :author=>"Mariano Azuela")
Book.create(:title =>"Pallieter", :author=>"Felix Timmermans")
Book.create(:title =>"Cuentos", :author=>"Horacio Quiroga")
Book.create(:title =>"Bendicion de la tierra", :author=>"Knut Hamsun")
Book.create(:title =>"El retorno del soldado", :author=>"Rebecca West")
Book.create(:title =>"Tarr", :author=>"Wyndham Lewis")
Book.create(:title =>"Tempestades de acero", :author=>"Ernst Junger")
Book.create(:title =>"Belarmino y Apolonio", :author=>"Ramon Perez de Ayala")
Book.create(:title =>"Nuestro padre San Daniel y El obispo leproso", :author=>"Gabriel Miro")
Book.create(:title =>"La edad de la inocencia", :author=>"Edith Wharton")
Book.create(:title =>"Los escandalos de Crome", :author=>"Aldous Huxley")
Book.create(:title =>"Historia de Cristo", :author=>"Giovanni Papini")
Book.create(:title =>"Ulises", :author=>"James Joyce")
Book.create(:title =>"Babbitt", :author=>"Sinclair Lewis")
Book.create(:title =>"La casa de Claudina", :author=>"Colette")
Book.create(:title =>"Life and Death of Harriett Frean", :author=>"")
Book.create(:title =>"El incongruente", :author=>"Ramon Gomez de la Serna")
Book.create(:title =>"Siddhartha", :author=>"Hermann Hesse")
Book.create(:title =>"La habitacion enorme", :author=>"E. E. Cummings")
Book.create(:title =>"Cristina, hija de Lavrans", :author=>"Sigrid Undset")
Book.create(:title =>"Amok", :author=>"Stefan Zweig")
Book.create(:title =>"El diablo en el cuerpo", :author=>"Raymond Radiguet")
Book.create(:title =>"La conciencia de Zeno", :author=>"Italo Svevo")
Book.create(:title =>"Pasaje a la India", :author=>"E. M. Forster")
Book.create(:title =>"Nosotros", :author=>"Evgueni Zamiatin")
Book.create(:title =>"La montana magica", :author=>"Thomas Mann")
Book.create(:title =>"El sombrero verde", :author=>"Michael Arlen")
Book.create(:title =>"Addis Alam", :author=>"Heruy Walda Sellase")
Book.create(:title =>"The Professor's House", :author=>"Willa Cather")
Book.create(:title =>"Los Artamonov", :author=>"Maximo Gorki")
Book.create(:title =>"El proceso", :author=>"Franz Kafka")
Book.create(:title =>"Los monederos falsos", :author=>"Andre Gide")
Book.create(:title =>"El gran Gatsby", :author=>"F. Scott Fitzgerald")
Book.create(:title =>"La senora Dalloway", :author=>"Virginia Woolf")
Book.create(:title =>"Chaka", :author=>"Thomas Mofolo")
Book.create(:title =>"Ser americanos", :author=>"Gertrude Stein")
Book.create(:title =>"El asesinato de Rogelio Ackroyd", :author=>"Agatha Christie")
Book.create(:title =>"Uno, ninguno y cien mil", :author=>"Luigi Pirandello")
Book.create(:title =>"Don Segundo Sombra", :author=>"Ricardo Guiraldes")
Book.create(:title =>"Las aventuras del valeroso soldado Schvejk", :author=>"Jaroslav Hasek")
Book.create(:title =>"Tirano Banderas", :author=>"Ramon Maria del Valle-Inclan")
Book.create(:title =>"El castillo", :author=>"Franz Kafka")
Book.create(:title =>"Blindness", :author=>"Henry Green")
Book.create(:title =>"Fiesta", :author=>"Ernest Hemingway")
Book.create(:title =>"America", :author=>"Franz Kafka")
Book.create(:title =>"La disputa por el sargento Grischa", :author=>"Arnold Zweig")
Book.create(:title =>"El lobo estepario", :author=>"Hermann Hesse")
Book.create(:title =>"Al faro", :author=>"Virginia Woolf")
Book.create(:title =>"En busca del tiempo perdido", :author=>"Marcel Proust")
Book.create(:title =>"El ruedo iberico", :author=>"Ramon Maria del Valle-Inclan")
Book.create(:title =>"Nadja", :author=>"Andre Breton")
Book.create(:title =>"Quicksand", :author=>"Nella Larsen")
Book.create(:title =>"Decadencia y caida", :author=>"Evelyn Waugh")
Book.create(:title =>"Hay quien prefiere las ortigas", :author=>"Junichiro Tanizaki")
Book.create(:title =>"Parade's End", :author=>"Ford Madox Ford")
Book.create(:title =>"El pozo de la soledad", :author=>"Radclyffe Hall")
Book.create(:title =>"El amante de lady Chatterley", :author=>"D.H. Lawrence")
Book.create(:title =>"Orlando", :author=>"Virginia Woolf")
Book.create(:title =>"Historia del ojo", :author=>"Georges Bataille")
Book.create(:title =>"Dona Barbara", :author=>"Romulo Gallegos")
Book.create(:title =>"Los ninos terribles", :author=>"Jean Cocteau")
Book.create(:title =>"Berlin Alexanderplatz", :author=>"Alfred Doblin")
Book.create(:title =>"Sin novedad en el frente", :author=>"Erich Maria Remarque")
Book.create(:title =>"Los indiferentes", :author=>"Alberto Moravia")
Book.create(:title =>"Living", :author=>"Henry Green")
Book.create(:title =>"Los siete locos", :author=>"Roberto Arlt")
Book.create(:title =>"Adios a las armas", :author=>"Ernest Hemingway")
Book.create(:title =>"Passing", :author=>"Nella Larsen")
Book.create(:title =>"El angel que nos mira", :author=>"Thomas Wolfe")
Book.create(:title =>"El halcon maltes", :author=>"Dashiell Hammett")
Book.create(:title =>"Iman", :author=>"Ramon J. Sender")
Book.create(:title =>"Los monos de imitacion de Dios", :author=>"Wyndham Lewis")
Book.create(:title =>"San Manuel Bueno, martir y tres historias mas", :author=>"Miguel de Unamuno")
Book.create(:title =>"Mort de dama", :author=>"Llorenc Villalonga")
Book.create(:title =>"Las olas", :author=>"Virginia Woolf")
Book.create(:title =>"Las lanzas coloradas", :author=>"Arturo Uslar Pietri")
Book.create(:title =>"El hombre delgado", :author=>"Dashiell Hammett")
Book.create(:title =>"Viaje al fin de la noche", :author=>"Louis-Ferdinand Celine")
Book.create(:title =>"Vida privada", :author=>"Josep Maria de Sagarra")
Book.create(:title =>"La marcha Radetzky", :author=>"Joseph Roth")
Book.create(:title =>"Laia", :author=>"Salvador Espriu")
Book.create(:title =>"La hija de Robert Poste", :author=>"Stella Gibbons")
Book.create(:title =>"Un mundo feliz", :author=>"Aldous Huxley")
Book.create(:title =>"Nudo de viboras", :author=>"Francois Mauriac")
Book.create(:title =>"El hombre sin atributos", :author=>"Robert Musil")
Book.create(:title =>"Queso", :author=>"Willem Elsschot")
Book.create(:title =>"La condicion humana", :author=>"Andre Malraux")
Book.create(:title =>"A Day Off", :author=>"Storm Jameson")
Book.create(:title =>"Testament of Youth", :author=>"Vera Brittain")
Book.create(:title =>"Autobiografia de Alice B. Toklas", :author=>"Gertrude Stein")
Book.create(:title =>"Muerte de un agente de publicidad", :author=>"Dorothy L. Sayers")
Book.create(:title =>"Huasipungo", :author=>"Jorge Icaza")
Book.create(:title =>"Llamalo sueno", :author=>"Henry Roth")
Book.create(:title =>"La calle de los cocodrilos", :author=>"Bruno Schulz")
Book.create(:title =>"Gracias, Jeeves", :author=>"P.G. Wodehouse")
Book.create(:title =>"Suave es la noche", :author=>"F. Scott Fitzgerald")
Book.create(:title =>"Tropico de Cancer", :author=>"Henry Miller")
Book.create(:title =>"El cartero siempre llama dos veces", :author=>"James M. Cain")
Book.create(:title =>"En las cimas de la desesperacion", :author=>"Emile M. Cioran")
Book.create(:title =>"Les cloches de Bale", :author=>"Louis Aragon")
Book.create(:title =>"Los nueve sastres", :author=>"Dorothy L. Sayers")
Book.create(:title =>"Auto de fe", :author=>"Elias Canetti")
Book.create(:title =>"Acaso no matan a los caballos?", :author=>"Horace McCoy")
Book.create(:title =>"Mr. Norris cambia de tren", :author=>"Christopher Isherwood")
Book.create(:title =>"El intocable", :author=>"Mulk Raj Anand")
Book.create(:title =>"Gente independiente", :author=>"Halldor Laxness")
Book.create(:title =>"El bosque de la noche", :author=>"Djuna Barnes")
Book.create(:title =>"En las montanas de la locura", :author=>"H.P. Lovecraft")
Book.create(:title =>"Absalon, Absalon", :author=>"William Faulkner")
Book.create(:title =>"La guerra de las salamandras", :author=>"Karel Capek")
Book.create(:title =>"Venciste, Rosemary", :author=>"George Orwell")
Book.create(:title =>"Lo que el viento se llevo", :author=>"Margaret Mitchell")
Book.create(:title =>"La cana que piensa", :author=>"Rebecca West")
Book.create(:title =>"Ciego en Gaza", :author=>"Aldous Huxley")
Book.create(:title =>"Summer Will Show", :author=>"Sylvia Townsend Warner")
Book.create(:title =>"Luotuo Xiangai", :author=>"Lao She")
Book.create(:title =>"Memorias de Africa", :author=>"Isak Dinesen (Karen Blixen)")
Book.create(:title =>"Entre parentesis", :author=>"David Jones")
Book.create(:title =>"Ferdydurke", :author=>"Witold Gombrowicz")
Book.create(:title =>"El buho ciego", :author=>"Sadeq Hedayat")
Book.create(:title =>"El Hobbit", :author=>"J.R.R. Tolkien")
Book.create(:title =>"Sus ojos miraban a Dios", :author=>"Zora Neale Hurston")
Book.create(:title =>"De ratones y hombres", :author=>"John Steinbeck")
Book.create(:title =>"Murphy", :author=>"Samuel Beckett")
Book.create(:title =>"U.S.A.", :author=>"John Dos Passos")
Book.create(:title =>"Brighton, parque de atracciones", :author=>"Graham Greene")
Book.create(:title =>"Motivo de alarma", :author=>"Eric Ambler")
Book.create(:title =>"Alamut", :author=>"Vladimir Bartol")
Book.create(:title =>"Rebeca", :author=>"Daphne du Maurier")
Book.create(:title =>"La nausea", :author=>"Jean-Paul Sartre")
Book.create(:title =>"Miss Pettigrew Lives for a Day", :author=>"Winifred Watson")
Book.create(:title =>"Na rubu pameti", :author=>"Miroslav Krleza")
Book.create(:title =>"El sueno eterno", :author=>"Raymond Chandler")
Book.create(:title =>"Adios a Berlin", :author=>"Christopher Isherwood")
Book.create(:title =>"Las uvas de la ira", :author=>"John Steinbeck")
Book.create(:title =>"Buenos dias, medianoche", :author=>"Jean Rhys")
Book.create(:title =>"En Nadar-dos-Pajaros", :author=>"Flann O'Brien")
Book.create(:title =>"Hijo nativo", :author=>"Richard Wright")
Book.create(:title =>"La invencion de Morel", :author=>"Adolfo Bioy Casares")
Book.create(:title =>"El desierto de los tartaros", :author=>"Dino Buzzati")
Book.create(:title =>"El poder y la gloria", :author=>"Graham Greene")
Book.create(:title =>"Por quien doblan las campanas", :author=>"Ernest Hemingway")
Book.create(:title =>"The Man Who Loved Children", :author=>"Christina Stead")
Book.create(:title =>"El mundo es ancho y ajeno", :author=>"Ciro Alegria")
Book.create(:title =>"Los vivos y los muertos", :author=>"Patrick White")
Book.create(:title =>"De tu tierra", :author=>"Cesare Pavese")
Book.create(:title =>"Cronica del alba", :author=>"Ramon J. Sender")
Book.create(:title =>"El extranjero", :author=>"Albert Camus")
Book.create(:title =>"El ultimo encuentro", :author=>"Sandor Marai")
Book.create(:title =>"El laberinto magico", :author=>"Max Aub")
Book.create(:title =>"El juego de los abalorios", :author=>"Hermann Hesse")
Book.create(:title =>"Jose y sus hermanos", :author=>"Thomas Mann")
Book.create(:title =>"El Principito", :author=>"Antoine de Saint-Exupery")
Book.create(:title =>"El hombre en suspenso", :author=>"Saul Bellow")
Book.create(:title =>"El filo de la navaja", :author=>"William Somerset Maugham")
Book.create(:title =>"Ficciones", :author=>"Jorge Luis Borges")
Book.create(:title =>"Pippi Calzaslargas", :author=>"Astrid Lindgren")
Book.create(:title =>"Memorias de Leticia Valle", :author=>"Rosa Chacel")
Book.create(:title =>"Rebelion en la granja", :author=>"George Orwell")
Book.create(:title =>"Un puente sobre el Drina", :author=>"Ivo Andric")
Book.create(:title =>"Cristo se detuvo en Eboli", :author=>"Carlo Levi")
Book.create(:title =>"Arcanum 17", :author=>"Andre Breton")
Book.create(:title =>"Retorno a Brideshead", :author=>"Evelyn Waugh")
Book.create(:title =>"Cronica de Travnik", :author=>"Ivo Andric")
Book.create(:title =>"La flauta de la lata", :author=>"Gabrielle Roy")
Book.create(:title =>"Nada", :author=>"Carmen Laforet")
Book.create(:title =>"La muerte de Virgilio", :author=>"Hermann Broch")
Book.create(:title =>"El senor presidente", :author=>"Miguel Angel Asturias")
Book.create(:title =>"Alexis Zorba", :author=>"Nikos Kazantzakis")
Book.create(:title =>"Back", :author=>"Henry Green")
Book.create(:title =>"El hombre perdido", :author=>"Ramon Gomez de la Serna")
Book.create(:title =>"El sendero de los nidos de arana", :author=>"Italo Calvino")
Book.create(:title =>"Bajo el volcan", :author=>"Malcolm Lowry")
Book.create(:title =>"Si esto es un hombre", :author=>"Primo Levi")
Book.create(:title =>"Ejercicios de estilo", :author=>"Raymond Queneau")
Book.create(:title =>"La peste", :author=>"Albert Camus")
Book.create(:title =>"Doktor Faustus", :author=>"Thomas Mann")
Book.create(:title =>"El callejon de los milagros", :author=>"Naguib Mahfuz")
Book.create(:title =>"La espuma de los dias", :author=>"Boris Vian")
Book.create(:title =>"Viaje a la Alcarria", :author=>"Camilo Jose Cela")
Book.create(:title =>"Cenizas y diamantes", :author=>"Jerzy Andrzejewski")
Book.create(:title =>"La desobediencia", :author=>"Alberto Moravia")
Book.create(:title =>"Adan Buenosayres", :author=>"Leopoldo Marechal")
Book.create(:title =>"Llanto por la tierra amada", :author=>"Alan Paton")
Book.create(:title =>"En el corazon de los mares", :author=>"Shmuel Yosef Agnon")
Book.create(:title =>"El tunel", :author=>"Ernesto Sabato")
Book.create(:title =>"La sentencia de muerte", :author=>"Maurice Blanchot")
Book.create(:title =>"1984", :author=>"George Orwell")
Book.create(:title =>"El hombre del brazo de oro", :author=>"Nelson Algren")
Book.create(:title =>"La cabeza del cordero", :author=>"Francisco Ayala")
Book.create(:title =>"The Heat of the Day", :author=>"Elizabeth Bowen")
Book.create(:title =>"Amor en un clima frio", :author=>"Nancy Mitford")
Book.create(:title =>"El caso Tulaev", :author=>"Victor Serge")
Book.create(:title =>"El Aleph", :author=>"Jorge Luis Borges")
Book.create(:title =>"Yo, robot", :author=>"Isaac Asimov")
Book.create(:title =>"Canta la hierba", :author=>"Doris Lessing")
Book.create(:title =>"Una ciudad como Alice", :author=>"Nevil Shute")
Book.create(:title =>"La luna y las fogatas", :author=>"Cesare Pavese")
Book.create(:title =>"Gormenghast", :author=>"Mervyn Peake")
Book.create(:title =>"Los trece relojes", :author=>"James Thurber")
Book.create(:title =>"El laberinto de la soledad", :author=>"Octavio Paz")
Book.create(:title =>"El cura C", :author=>"Georges Bataille")
Book.create(:title =>"Los inocentes", :author=>"Hermann Broch")
Book.create(:title =>"La colmena", :author=>"Camilo Jose Cela")
Book.create(:title =>"El fin de la aventura", :author=>"Graham Greene")
Book.create(:title =>"Molloy", :author=>"Samuel Beckett")
Book.create(:title =>"El hombre rebelde", :author=>"Albert Camus")
Book.create(:title =>"El guardian entre el centeno", :author=>"J.D. Salinger")
Book.create(:title =>"El mar de las Sirtes", :author=>"Julien Gracq")
Book.create(:title =>"Fundacion", :author=>"Isaac Asimov")
Book.create(:title =>"Malone muere", :author=>"Samuel Beckett")
Book.create(:title =>"El dia de los trifidos", :author=>"John Wyndham")
Book.create(:title =>"Memorias de Adriano", :author=>"Marguerite Yourcenar")
Book.create(:title =>"El asesino dentro de mi", :author=>"Jim Thompson")
Book.create(:title =>"Sangre sabia", :author=>"Flannery O'Connor")
Book.create(:title =>"El viejo y el mar", :author=>"Ernest Hemingway")
Book.create(:title =>"El hombre invisible", :author=>"Ralph Ellison")
Book.create(:title =>"El juez y su verdugo", :author=>"Friedrich Durrenmatt")
Book.create(:title =>"Confabulario", :author=>"Juan Jose Arreola")
Book.create(:title =>"Mil grullas", :author=>"Yasunari Kawabata")
Book.create(:title =>"Ve y dilo en la montana", :author=>"James Baldwin")
Book.create(:title =>"Casino Royale", :author=>"Ian Fleming")
Book.create(:title =>"Yonqui", :author=>"William Burroughs")
Book.create(:title =>"Jim buena suerte", :author=>"Kingsley Amis")
Book.create(:title =>"Los pasos perdidos", :author=>"Alejo Carpentier")
Book.create(:title =>"El invernadero", :author=>"Wolfgang Koeppen")
Book.create(:title =>"El largo adios", :author=>"Raymond Chandler")
Book.create(:title =>"El llano en llamas", :author=>"Juan Rulfo")
Book.create(:title =>"Requiem por un campesino espanol", :author=>"Ramon J. Sender")
Book.create(:title =>"Pomladni dan", :author=>"Ciril Kosmac")
Book.create(:title =>"El desprecio", :author=>"Alberto Moravia")
Book.create(:title =>"Historia de O", :author=>"Pauline Reage")
Book.create(:title =>"Bajo la red", :author=>"Iris Murdoch")
Book.create(:title =>"El senor de las moscas", :author=>"William Golding")
Book.create(:title =>"Los mandarines", :author=>"Simone de Beauvoir")
Book.create(:title =>"Buenos dias tristeza", :author=>"Francoise Sagan")
Book.create(:title =>"El sueno de los heroes", :author=>"Adolfo Bioy Casares")
Book.create(:title =>"El rumor del oleaje", :author=>"Yukio Mishima")
Book.create(:title =>"Los bravos", :author=>"Jesus Fernandez Santos")
Book.create(:title =>"Rosaura a las diez", :author=>"Marco Denevi")
Book.create(:title =>"Chicos del arroyo", :author=>"Pier Paolo Pasolini")
Book.create(:title =>"Los reconocimientos", :author=>"William Gaddis")
Book.create(:title =>"Pedro Paramo", :author=>"Juan Rulfo")
Book.create(:title =>"El americano impasible", :author=>"Graham Greene")
Book.create(:title =>"Cronicas de la verdad oculta", :author=>"Pere Calders")
Book.create(:title =>"El halcon", :author=>"Yasar Kemal")
Book.create(:title =>"La ultima tentacion de Cristo", :author=>"Nikos Kazantzakis")
Book.create(:title =>"Gran Serton: veredas", :author=>"Joao Guimaraes Rosa")
Book.create(:title =>"Lolita", :author=>"Vladimir Nabokov")
Book.create(:title =>"El talento de Mr. Ripley", :author=>"Patricia Highsmith")
Book.create(:title =>"El Senor de los Anillos", :author=>"J.R.R. Tolkien")
Book.create(:title =>"The Lonely Londoners", :author=>"Sam Selvon")
Book.create(:title =>"Incierta gloria", :author=>"Joan Sales")
Book.create(:title =>"El Jarama", :author=>"Rafael Sanchez Ferlosio")
Book.create(:title =>"La habitacion de Giovanni", :author=>"James Baldwin")
Book.create(:title =>"Justine", :author=>"Lawrence Durrell")
Book.create(:title =>"Abejas de cristal", :author=>"Ernst Junger")
Book.create(:title =>"El doctor Zhivago", :author=>"Boris Pasternak")
Book.create(:title =>"Pnin", :author=>"Vladimir Nabokov")
Book.create(:title =>"En la carretera", :author=>"Jack Kerouac")
Book.create(:title =>"Gran sol", :author=>"Ignacio Aldecoa")
Book.create(:title =>"Los gozos y las sombras", :author=>"Gonzalo Torrente Ballester")
Book.create(:title =>"Homo Faber", :author=>"Max Frisch")
Book.create(:title =>"El azul del cielo", :author=>"Georges Bataille")
Book.create(:title =>"Los cucos de Midwich", :author=>"John Wyndham")
Book.create(:title =>"Tierra ignota", :author=>"Patrick White")
Book.create(:title =>"La celosia", :author=>"Alain Robbe-Grillet")
Book.create(:title =>"Merlin y familia", :author=>"Alvaro Cunqueiro")
Book.create(:title =>"Camelot", :author=>"T.H. White")
Book.create(:title =>"La campana", :author=>"Iris Murdoch")
Book.create(:title =>"Confesiones de un rebelde irlandes", :author=>"Brendan Behan")
Book.create(:title =>"Gabriela, clavo y canela", :author=>"Jorge Amado")
Book.create(:title =>"Sabado por la noche y domingo por la manana", :author=>"Alan Sillitoe")
Book.create(:title =>"Todo se desmorona", :author=>"Chinua Achebe")
Book.create(:title =>"The Bitter Glass", :author=>"Eilis Dillon")
Book.create(:title =>"El guia", :author=>"R.K. Narayan")
Book.create(:title =>"El gatopardo", :author=>"Giuseppe Tomasi de Lampedusa")
Book.create(:title =>"Los rios profundos", :author=>"Jose Maria Arguedas")
Book.create(:title =>"Desayuno en Tiffany's", :author=>"Truman Capote")
Book.create(:title =>"La parranda", :author=>"Eduardo Blanco Amor")
Book.create(:title =>"Billar a las nueve y media", :author=>"Heinrich Boll")
Book.create(:title =>"Obras completas (y otros cuentos)", :author=>"Augusto Monterroso")
Book.create(:title =>"Sidra con Rosie", :author=>"Laurie Lee")
Book.create(:title =>"El tambor de hojalata", :author=>"Gunter Grass")
Book.create(:title =>"El almuerzo desnudo", :author=>"William Burroughs")
Book.create(:title =>"Billy Liar", :author=>"Keith Waterhouse")
Book.create(:title =>"Las armas secretas", :author=>"Julio Cortazar")
Book.create(:title =>"La promesa del alba", :author=>"Romain Gary")
Book.create(:title =>"Corre, Conejo", :author=>"John Updike")
Book.create(:title =>"Matar un ruisenor", :author=>"Harper Lee")
Book.create(:title =>"El mago de Lublin", :author=>"Isaac Bashevis Singer")
Book.create(:title =>"Halbzeit", :author=>"Martin Walser")
Book.create(:title =>"The Country Girls", :author=>"Edna O'Brien")
Book.create(:title =>"Primera memoria", :author=>"Ana Maria Matute")
Book.create(:title =>"Las historias naturales", :author=>"Joan Perucho")
Book.create(:title =>"El astillero", :author=>"Juan Carlos Onetti")
Book.create(:title =>"Trampa 22", :author=>"Joseph Heller")
Book.create(:title =>"Solaris", :author=>"Stanislaw Lem")
Book.create(:title =>"El gato y el raton", :author=>"Gunter Grass")
Book.create(:title =>"The Prime of Miss Jean Brodie", :author=>"Muriel Spark")
Book.create(:title =>"Cabeza cortada", :author=>"Iris Murdoch")
Book.create(:title =>"Bearn o la sala de las munecas", :author=>"Llorenc Villalonga")
Book.create(:title =>"Memorias de un nino campesino", :author=>"Xose Neira Vilas")
Book.create(:title =>"Sobre heroes y tumbas", :author=>"Ernesto Sabato")
Book.create(:title =>"El siglo de las luces", :author=>"Alejo Carpentier")
Book.create(:title =>"Las ratas", :author=>"Miguel Delibes")
Book.create(:title =>"Bomarzo", :author=>"Manuel Mujica Lainez")
Book.create(:title =>"El cuaderno dorado", :author=>"Doris Lessing")
Book.create(:title =>"Tiempo de silencio", :author=>"Luis Martin Santos")
Book.create(:title =>"Palido fuego", :author=>"Vladimir Nabokov")
Book.create(:title =>"La naranja mecanica", :author=>"Anthony Burgess")
Book.create(:title =>"Alguien volo sobre el nido del cuco", :author=>"Ken Kesey")
Book.create(:title =>"Girl with Green Eyes", :author=>"Edna O'Brien")
Book.create(:title =>"La muerte de Artemio Cruz", :author=>"Carlos Fuentes")
Book.create(:title =>"La plaza del Diamante", :author=>"Merce Rodoreda")
Book.create(:title =>"La ciudad y los perros", :author=>"Mario Vargas Llosa")
Book.create(:title =>"Un dia en la vida de Ivan Denisovich", :author=>"Alexandr Solzhenitsin")
Book.create(:title =>"Rayuela", :author=>"Julio Cortazar")
Book.create(:title =>"Los pasos contados", :author=>"Corpus Barga")
Book.create(:title =>"La campana de cristal", :author=>"Sylvia Plath")
Book.create(:title =>"Enderby por dentro", :author=>"Anthony Burgess")
Book.create(:title =>"Las senoritas de escasos medios", :author=>"Muriel Spark")
Book.create(:title =>"El espia que surgio del frio", :author=>"John Le Carre")
Book.create(:title =>"Manon des Sources", :author=>"Marcel Pagnol")
Book.create(:title =>"El graduado", :author=>"Charles Webb")
Book.create(:title =>"Cuna de gato", :author=>"Kurt Vonnegut, Jr.")
Book.create(:title =>"V.", :author=>"Thomas Pynchon")
Book.create(:title =>"Herzog", :author=>"Saul Bellow")
Book.create(:title =>"El arrebato de Lol von Stein", :author=>"Marguerite Duras")
Book.create(:title =>"Arrow of God", :author=>"Chinua Achebe")
Book.create(:title =>"A veces un gran impulso", :author=>"Ken Kesey")
Book.create(:title =>"Tres tristes tigres", :author=>"Guillermo Cabrera Infante")
Book.create(:title =>"La pasion segun G.H.", :author=>"Clarice Lispector")
Book.create(:title =>"Gracias por el fuego", :author=>"Mario Benedetti")
Book.create(:title =>"Trenes rigurosamente vigilados", :author=>"Bohumil Hrabal")
Book.create(:title =>"The River Between", :author=>"Ngugi Wa Thiong'o")
Book.create(:title =>"Basta, pepeo", :author=>"Danilo Kis")
Book.create(:title =>"Todo lo que crece tiene que converger", :author=>"Flannery O'Connor")
Book.create(:title =>"Las cosas", :author=>"Georges Perec")
Book.create(:title =>"A sangre fria", :author=>"Truman Capote")
Book.create(:title =>"Paradiso", :author=>"Jose Lezama Lima")
Book.create(:title =>"Ultimas tardes con Teresa", :author=>"Juan Marse")
Book.create(:title =>"A cada cual lo suyo", :author=>"Leonardo Sciascia")
Book.create(:title =>"La subasta del lote 49", :author=>"Thomas Pynchon")
Book.create(:title =>"Giles Goat-Boy", :author=>"John Barth")
Book.create(:title =>"Senas de identidad", :author=>"Juan Goytisolo")
Book.create(:title =>"Cinco horas con Mario", :author=>"Miguel Delibes")
Book.create(:title =>"El cuaderno gris", :author=>"Josep Pla")
Book.create(:title =>"El maestro y Margarita", :author=>"Mijail Bulgakov")
Book.create(:title =>"Ancho mar de los Sargazos", :author=>"Jean Rhys")
Book.create(:title =>"El tercer policia", :author=>"Flann O'Brien")
Book.create(:title =>"Miramar", :author=>"Naguib Mahfuz")
Book.create(:title =>"Z", :author=>"Vassilis Vassilikos")
Book.create(:title =>"Pilgrimage", :author=>"Dorothy Richardson")
Book.create(:title =>"La casa de Jampol", :author=>"Isaac Bashevis Singer")
Book.create(:title =>"Cien anos de soledad", :author=>"Gabriel Garcia Marquez")
Book.create(:title =>"No Laughing Matter", :author=>"Angus Wilson")
Book.create(:title =>"Un animal dotado de razon", :author=>"Robert Merle")
Book.create(:title =>"Ponche de acido lisergico", :author=>"Tom Wolfe")
Book.create(:title =>"Eva Trout", :author=>"Elizabeth Bowen")
Book.create(:title =>"Volveras a Region", :author=>"Juan Benet")
Book.create(:title =>"A Kestrel for a Knave", :author=>"Barry Hines")
Book.create(:title =>"In Watermelon Sugar", :author=>"Richard Brautigan")
Book.create(:title =>"Leccion de aleman", :author=>"Siegfried Lenz")
Book.create(:title =>"Noticias sobre Christa T.", :author=>"Christa Wolf")
Book.create(:title =>"Suenan los androides con ovejas electricas?", :author=>"Philip K. Dick")
Book.create(:title =>"2001: Una odisea del espacio", :author=>"Arthur C. Clarke")
Book.create(:title =>"Bella del senor", :author=>"Albert Cohen")
Book.create(:title =>"Pabellon de cancer", :author=>"Alexandr Solzhenitsin")
Book.create(:title =>"Myra Breckinridge", :author=>"Gore Vidal")
Book.create(:title =>"El primer circulo", :author=>"Alexandr Solzhenitsin")
Book.create(:title =>"El secuestro", :author=>"Georges Perec")
Book.create(:title =>"them", :author=>"Joyce Carol Oates")
Book.create(:title =>"Ada o el ardor", :author=>"Vladimir Nabokov")
Book.create(:title =>"El padrino", :author=>"Mario Puzo")
Book.create(:title =>"El lamento de Portnoy", :author=>"Philip Roth")
Book.create(:title =>"El dia que murio Marilyn", :author=>"Terenci Moix")
Book.create(:title =>"La mujer del teniente frances", :author=>"John Fowles")
Book.create(:title =>"Matadero cinco", :author=>"Kurt Vonnegut")
Book.create(:title =>"Un ciego con una pistola", :author=>"Chester Himes")
Book.create(:title =>"El hurgon magico", :author=>"Robert Coover")
Book.create(:title =>"Tienda de los milagros", :author=>"Jorge Amado")
Book.create(:title =>"A latogato", :author=>"Gyorgy Konrad")
Book.create(:title =>"Moscu-Petushki", :author=>"Venedikt Yerofeev")
Book.create(:title =>"Boquitas pintadas", :author=>"Manuel Puig")
Book.create(:title =>"Mawsim al-hijrah ila'l-shamal", :author=>"Tayeb Salih")
Book.create(:title =>"Hasta no verte, Jesus mio", :author=>"Elena Poniatowska")
Book.create(:title =>"El informe de Brodie", :author=>"Jorge Luis Borges")
Book.create(:title =>"El rey de los alisos", :author=>"Michel Tournier")
Book.create(:title =>"Jahrestage", :author=>"Uwe Johnson")
Book.create(:title =>"Un mundo para Julius", :author=>"Alfredo Bryce Echenique")
Book.create(:title =>"Yo se por que canta el pajaro enjaulado", :author=>"Maya Angelou")
Book.create(:title =>"Ojos azules", :author=>"Toni Morrison")
Book.create(:title =>"El mar de la fertilidad", :author=>"Yukio Mishima")
Book.create(:title =>"El regreso de Conejo", :author=>"John Updike")
Book.create(:title =>"Bilmo", :author=>"Mykhaylo Osadchyl")
Book.create(:title =>"Retrato de grupo con senora", :author=>"Heinrich Boll")
Book.create(:title =>"Miedo y asco en Las Vegas", :author=>"Hunter S. Thompson")
Book.create(:title =>"El libro de Daniel", :author=>"E.L. Doctorow")
Book.create(:title =>"En un estado libre", :author=>"V.S. Naipul")
Book.create(:title =>"House Mother Normal: A Geriatric Comedy", :author=>"B.S. Johnson")
Book.create(:title =>"Cobra", :author=>"Severo Sarduy")
Book.create(:title =>"Resurgir", :author=>"Margaret Atwood")
Book.create(:title =>"G.", :author=>"John Berger")
Book.create(:title =>"El gran momento de Mary Tribune", :author=>"Juan Garcia Hortelano")
Book.create(:title =>"Kokotsu no hito", :author=>"Sawako Ariyoshi")
Book.create(:title =>"Las ciudades invisibles", :author=>"Italo Calvino")
Book.create(:title =>"Si te dicen que cai", :author=>"Juan Marse")
Book.create(:title =>"El arco iris de gravedad", :author=>"Thomas Pynchon")
Book.create(:title =>"El consul honorario", :author=>"Graham Greene")
Book.create(:title =>"Crash", :author=>"J.G. Ballard")
Book.create(:title =>"El castillo de los destinos cruzados", :author=>"Italo Calvino")
Book.create(:title =>"Antagonia", :author=>"Luis Goytisolo")
Book.create(:title =>"A Question of Power", :author=>"Bessie Head")
Book.create(:title =>"Miedo a volar", :author=>"Erica Jong")
Book.create(:title =>"Yo el Supremo", :author=>"Augusto Roa Bastos")
Book.create(:title =>"Escuela de mandarines", :author=>"Miguel Espinosa")
Book.create(:title =>"El honor perdido de Katharina Blum", :author=>"Heinrich Boll")
Book.create(:title =>"Tierras en penumbra", :author=>"J.M. Coetzee")
Book.create(:title =>"Agata ojo de gato", :author=>"Jose Manuel Caballero Bonald")
Book.create(:title =>"Ragtime", :author=>"E.L. Doctorow")
Book.create(:title =>"Luka", :author=>"Antun Soljan")
Book.create(:title =>"Icaria, Icaria", :author=>"Xavier Benguerel")
Book.create(:title =>"El ano de la liebre", :author=>"Arto Paasilinna")
Book.create(:title =>"El legado de Humboldt", :author=>"Saul Bellow")
Book.create(:title =>"Mortal y rosa", :author=>"Francisco Umbral")
Book.create(:title =>"Willard y sus trofeos de bolos", :author=>"Richard Brautigan")
Book.create(:title =>"Sin destino", :author=>"Imre Kertesz")
Book.create(:title =>"The Dead Father", :author=>"Donal Barthelme")
Book.create(:title =>"La verdad sobre el caso Savolta", :author=>"Eduardo Mendoza")
Book.create(:title =>"Una danza para la musica del tiempo", :author=>"Anthony Powell")
Book.create(:title =>"Te dejo el mar", :author=>"Carme Riera")
Book.create(:title =>"El otono del patriarca", :author=>"Gabriel Garcia Marquez")
Book.create(:title =>"Muestra de infancia", :author=>"Christa Wolf")
Book.create(:title =>"Las delicias de la maternidad", :author=>"Buchi Emecheta")
Book.create(:title =>"Cutter and Bone", :author=>"Newton Thornburg")
Book.create(:title =>"Entrevista con el vampiro", :author=>"Anne Rice")
Book.create(:title =>"La mujer zurda", :author=>"Peter Handke")
Book.create(:title =>"El beso de la mujer arana", :author=>"Manuel Puig")
Book.create(:title =>"Azul casi transparente", :author=>"Ryu Murakami")
Book.create(:title =>"Vision del ahogado", :author=>"Juan Jose Millas")
Book.create(:title =>"El ingeniero de almas", :author=>"Josef skvorecky")
Book.create(:title =>"La esposa americana", :author=>"Mario Soldati")
Book.create(:title =>"La hora de la estrella", :author=>"Clarice Lispector")
Book.create(:title =>"La cancion de Salomon", :author=>"Toni Morrison")
Book.create(:title =>"Las guerras", :author=>"Timothy Findley")
Book.create(:title =>"Despachos de guera", :author=>"Michael Herr")
Book.create(:title =>"El resplandor", :author=>"Stephen King")
Book.create(:title =>"Delta de Venus", :author=>"Anais Nin")
Book.create(:title =>"Silvio en El Rosedal", :author=>"Julio Ramon Ribeyro")
Book.create(:title =>"Una bandada de zarapitos", :author=>"Maarten't Hart")
Book.create(:title =>"The Singapore Grip", :author=>"J.G. Farrell")
Book.create(:title =>"El mar, el mar", :author=>"Iris Murdoch")
Book.create(:title =>"La vida: instrucciones de uso", :author=>"Georges Perec")
Book.create(:title =>"El cuarto de atras", :author=>"Carmen Martin Gaite")
Book.create(:title =>"Los convidados de piedra", :author=>"Jorge Edwards")
Book.create(:title =>"Jardin de cemento", :author=>"Ian McEwan")
Book.create(:title =>"Guia del autoestopista galactico", :author=>"Douglas Adams")
Book.create(:title =>"Si una noche de invierno un viajero", :author=>"Italo Calvino")
Book.create(:title =>"La gente de Smiley", :author=>"John Le Carre")
Book.create(:title =>"La hija de Burger", :author=>"Nadine Gordimer")
Book.create(:title =>"A Bend in the River", :author=>"V.S. Naipul")
Book.create(:title =>"A Dry White Season", :author=>"Andre Brink")
Book.create(:title =>"El libro de la risa y el olvido", :author=>"Milan Kundera")
Book.create(:title =>"Asedio preventivo", :author=>"Heinrich Boll")
Book.create(:title =>"Shikasta", :author=>"Doris Lessing")
Book.create(:title =>"Los mares del sur", :author=>"Manuel Vazquez Montalban")
Book.create(:title =>"El nombre de la rosa", :author=>"Umberto Eco")
Book.create(:title =>"Respiracion artificial", :author=>"Ricardo Piglia")
Book.create(:title =>"La conjura de los necios", :author=>"John Kennedy Toole")
Book.create(:title =>"Rituales", :author=>"Cees Nooteboom")
Book.create(:title =>"Saul ante Samuel", :author=>"Juan Benet")
Book.create(:title =>"Abril quebrado", :author=>"Ismail Kadare")
Book.create(:title =>"Hijos de la medianoche", :author=>"Salman Rushdie")
Book.create(:title =>"Esperando a los barbaros", :author=>"J.M. Coetzee")
Book.create(:title =>"No habra mas penas ni olvido", :author=>"Osvaldo Soriano")
Book.create(:title =>"Octubre, octubre", :author=>"Jose Luis Sampedro")
Book.create(:title =>"El rio de la luna", :author=>"Jose Maria Guelbenzu")
Book.create(:title =>"La guerra del fin del mundo", :author=>"Mario Vargas Llosa")
Book.create(:title =>"Lanark, una vida en cuatro libros", :author=>"Alasdair Gray")
Book.create(:title =>"Conejo es rico", :author=>"John Updike")
Book.create(:title =>"Parejas, transeuntes", :author=>"Botho Strauss")
Book.create(:title =>"La gente de July", :author=>"Nadine Gordimer")
Book.create(:title =>"Colina negra", :author=>"Bruce Chatwin")
Book.create(:title =>"La casa de los espiritus", :author=>"Isabel Allende")
Book.create(:title =>"La lista de Schindler", :author=>"Thomas Keneally")
Book.create(:title =>"Palida luz en las colinas", :author=>"Kazuo Ishiguro")
Book.create(:title =>"El sobrino de Wittgenstein", :author=>"Thomas Bernhard")
Book.create(:title =>"El color purpura", :author=>"Alice Walker")
Book.create(:title =>"La historia particular de un muchacho", :author=>"Edmund White")
Book.create(:title =>"Si ahora no, cuando?", :author=>"Primo Levi")
Book.create(:title =>"Libro del desasosiego", :author=>"Fernando Pessoa")
Book.create(:title =>"Memorial del convento", :author=>"Jose Saramago")
Book.create(:title =>"La pena de Belgica", :author=>"Hugo Claus")
Book.create(:title =>"La pianista", :author=>"Elfriede Jelinek")
Book.create(:title =>"Vida y epoca de Michael K", :author=>"J.M. Coetzee")
Book.create(:title =>"El pais del agua", :author=>"Graham Swift")
Book.create(:title =>"Larva. Babel de una noche de San Juan", :author=>"Julian Rios")
Book.create(:title =>"El oratorio de Navidad", :author=>"Goran Tunstrom")
Book.create(:title =>"Fado Alexandrino", :author=>"Antonio Lobo Antunes")
Book.create(:title =>"El entenado", :author=>"Juan Jose Saer")
Book.create(:title =>"Verguenza", :author=>"Salman Rushdie")
Book.create(:title =>"Dinero", :author=>"Martin Amis")
Book.create(:title =>"El loro de Flaubert", :author=>"Julian Barnes")
Book.create(:title =>"La partida del profesor Martens", :author=>"Jean Kross")
Book.create(:title =>"Aborto en la escuela", :author=>"Kathy Acker")
Book.create(:title =>"Noches en el circo", :author=>"Angela Carter")
Book.create(:title =>"El Griffon", :author=>"Alfredo Conde")
Book.create(:title =>"Neuromante", :author=>"William Gibson")
Book.create(:title =>"La fabrica de las avispas", :author=>"Iain Banks")
Book.create(:title =>"El imperio del sol", :author=>"J.G. Ballard")
Book.create(:title =>"El amante", :author=>"Marguerite Duras")
Book.create(:title =>"El ano de la muerte de Ricardo Reis", :author=>"Jose Saramago")
Book.create(:title =>"Ciclo de Drenai, 1. Waylander", :author=>"David Gremmell")
Book.create(:title =>"The Busconductor Hines", :author=>"James Kelman")
Book.create(:title =>"Diccionario jazaro: novela-lexico en 100.000 palabras", :author=>"Milorad Pavic")
Book.create(:title =>"La insoportable levedad del ser", :author=>"Milan Kundera")
Book.create(:title =>"El heroe de las mansardas de Mansard", :author=>"Alvaro Pombo")
Book.create(:title =>"El hombre joven", :author=>"Botho Strauss")
Book.create(:title =>"La mitad del hombre es la mujer", :author=>"Zang Xianliang")
Book.create(:title =>"Ruido de fondo", :author=>"Don DeLillo")
Book.create(:title =>"El desfile del amor", :author=>"Sergio Pitol")
Book.create(:title =>"Amado monstruo", :author=>"Javier Tomeo")
Book.create(:title =>"El cuento de la criada", :author=>"Margaret Atwood")
Book.create(:title =>"La sombra de Hawksmoor", :author=>"Peter Ackroyd")
Book.create(:title =>"El perfume", :author=>"Patrick Suskind")
Book.create(:title =>"Beyaz Kale", :author=>"Orhan Pamuk")
Book.create(:title =>"Contacto", :author=>"Carl Sagan")
Book.create(:title =>"La historia de Simon", :author=>"Marianne Frediksson")
Book.create(:title =>"Las normas de la casa de la sidra", :author=>"John Irving")
Book.create(:title =>"La orilla oscura", :author=>"Jose Maria Merino")
Book.create(:title =>"Der Blindensturz", :author=>"Gert Hofmann")
Book.create(:title =>"El amor en los tiempos del colera", :author=>"Gabriel Garcia Marquez")
Book.create(:title =>"Beatus ille", :author=>"Antonio Munoz Molina")
Book.create(:title =>"La bella senora Seidenman", :author=>"Andrzej Szczypioski")
Book.create(:title =>"Los hundidos y los salvados", :author=>"Primo Levi")
Book.create(:title =>"La fuente de la edad", :author=>"Luis Mateo Diez")
Book.create(:title =>"Extincion: un desmoronamiento", :author=>"Thomas Bernhard")
Book.create(:title =>"Un artista del mundo flotante", :author=>"Kazuo Ishiguro")
Book.create(:title =>"Watchmen", :author=>"Alan Moore & Dave Gibbons")
Book.create(:title =>"Los viejos demonios", :author=>"Kingsley Amis")
Book.create(:title =>"Matigari", :author=>"Ngugi Wa Thiong'o")
Book.create(:title =>"Anagramas", :author=>"Lorrie Moore")
Book.create(:title =>"El lenguaje perdido de las gruas", :author=>"David Leavitt")
Book.create(:title =>"Todas las almas", :author=>"Javier Marias")
Book.create(:title =>"Balada za Georg Henih", :author=>"Viktor Paskov")
Book.create(:title =>"El enigma de la llegada", :author=>"V.S. Naipaul")
Book.create(:title =>"El fin del mundo", :author=>"T. Coraghessan Boyle")
Book.create(:title =>"La paloma", :author=>"Patrick Suskind")
Book.create(:title =>"Noticias del Imperio", :author=>"Fernando del Paso")
Book.create(:title =>"Beloved", :author=>"Toni Morrison")
Book.create(:title =>"Taebaek Sanmaek", :author=>"Jo Jung-rae")
Book.create(:title =>"La trilogia de Nueva York", :author=>"Paul Auster")
Book.create(:title =>"La caja negra", :author=>"Amos Oz")
Book.create(:title =>"La feria de las vanidades", :author=>"Tom Wolfe")
Book.create(:title =>"La dalia negra", :author=>"James Ellroy")
Book.create(:title =>"La tarde de un escritor", :author=>"Peter Handke")
Book.create(:title =>"El camino radiante", :author=>"Margaret Drabble")
Book.create(:title =>"Kitchen", :author=>"Banana Yoshimoto")
Book.create(:title =>"Dirk Gently: Agencia de investigaciones holisticas", :author=>"Douglas Adams")
Book.create(:title =>"Cigarettes", :author=>"Harry Matthews")
Book.create(:title =>"Nervous Conditions", :author=>"Tsitsi Dangarembga")
Book.create(:title =>"Camino de sirga", :author=>"Jesus Moncada")
Book.create(:title =>"El ultimo mundo", :author=>"Christoph Ransmayr")
Book.create(:title =>"Oscar y Lucinda", :author=>"Peter Carey")
Book.create(:title =>"La biblioteca de la piscina", :author=>"Allan Hollinghurst")
Book.create(:title =>"Los versos satanicos", :author=>"Salman Rushdie")
Book.create(:title =>"Obabakoak", :author=>"Bernardo Atxaga")
Book.create(:title =>"Los paraisos ciegos", :author=>"Duong Thu Huong")
Book.create(:title =>"El pendulo de Foucault", :author=>"Umberto Eco")
Book.create(:title =>"Gimmick", :author=>"Joost Zwagerman")
Book.create(:title =>"El jardin de los siete crepusculos", :author=>"Miquel de Palol")
Book.create(:title =>"Inland", :author=>"Gerald Murnane")
Book.create(:title =>"Oracion por Owen", :author=>"John Irving")
Book.create(:title =>"Como agua para chocolate", :author=>"Laura Esquivel")
Book.create(:title =>"Historia del cerco de Lisboa", :author=>"Jose Saramago")
Book.create(:title =>"La magnitud de la tragedia", :author=>"Quim Monzo")
Book.create(:title =>"Juegos de la edad tardia", :author=>"Luis Landero")
Book.create(:title =>"Melancolia de la resistencia", :author=>"Laszlo Krasznahorkai")
Book.create(:title =>"Los restos del dia", :author=>"Kazuo Ishiguro")
Book.create(:title =>"Campos de Londres", :author=>"Martin Amis")
Book.create(:title =>"El palacio de la luna", :author=>"Paul Auster")
Book.create(:title =>"Espejismos", :author=>"Jeannette Winterson")
Book.create(:title =>"Como la vida misma", :author=>"Lorrie Moore")
Book.create(:title =>"El buda de los suburbios", :author=>"Hanif Kureishi")
Book.create(:title =>"Lineas de sombra", :author=>"Amitav Ghosh")
Book.create(:title =>"El metro de platino iridiado", :author=>"Alvaro Pombo")
Book.create(:title =>"Amongst Women", :author=>"John McGahern")
Book.create(:title =>"La musica del azar", :author=>"Paul Auster")
Book.create(:title =>"Stone Junction", :author=>"Jim Dodge")
Book.create(:title =>"Un millon de vacas", :author=>"Manuel Rivas")
Book.create(:title =>"Como conquistar Hollywood", :author=>"Elmore Leonard")
Book.create(:title =>"Memorias de una hija de perra", :author=>"Pavlos Matesis")
Book.create(:title =>"Vertigo", :author=>"W.G. Sebald")
Book.create(:title =>"American Psycho", :author=>"Bret Easton Ellis")
Book.create(:title =>"The Laws", :author=>"Connie Palmen")
Book.create(:title =>"Asesinos sin rostro", :author=>"Henning Mankell")
Book.create(:title =>"Astradeni", :author=>"Eugenia Fakinou")
Book.create(:title =>"La liebre", :author=>"Cesar Aira")
Book.create(:title =>"Typical", :author=>"Padgett Powell")
Book.create(:title =>"Mao II", :author=>"Don DeLillo")
Book.create(:title =>"Cisnes salvajes", :author=>"Jung Chang")
Book.create(:title =>"Arcadia", :author=>"Jim Crace")
Book.create(:title =>"Una infancia en Marraquech", :author=>"Esther Freud")
Book.create(:title =>"Memoirs of Rain", :author=>"Sunetra Gupta")
Book.create(:title =>"Asphodel", :author=>"H.D.")
Book.create(:title =>"El aprendiz de carnicero", :author=>"Patrick McCabe")
Book.create(:title =>"La senorita Smila y su especial percepcion de la nieve", :author=>"Peter Hoeg")
Book.create(:title =>"Corazon tan blanco", :author=>"Javier Marias")
Book.create(:title =>"Escrito en el cuerpo", :author=>"Jeanette Winterson")
Book.create(:title =>"The Crow Road", :author=>"Iain Banks")
Book.create(:title =>"Indigo", :author=>"Marina Warner")
Book.create(:title =>"El paciente ingles", :author=>"Michael Ondaatje")
Book.create(:title =>"En posesion del secreto de la alegria", :author=>"Alice Walker")
Book.create(:title =>"Las piranas", :author=>"Miguel Sanchez-Ostiz")
Book.create(:title =>"The Triple Mirror of the Self", :author=>"Zulfikar Ghose")
Book.create(:title =>"Tio Petros y la conjetura de Goldbach", :author=>"Apostolos Doxiadis")
Book.create(:title =>"El descubrimiento del cielo", :author=>"Harry Mulisch")
Book.create(:title =>"La vida es un caravasar", :author=>"Emine Sevgi Ozdamar")
Book.create(:title =>"Antes que anochezca", :author=>"Reinaldo Arenas")
Book.create(:title =>"El secreto", :author=>"Donna Tartt")
Book.create(:title =>"Empresas y tribulaciones de Maqroll el Gaviero", :author=>"Alvaro Mutis")
Book.create(:title =>"El club Dumas", :author=>"Arturo Perez-Reverte")
Book.create(:title =>"Vidas de santos", :author=>"Rodrigo Fresan")
Book.create(:title =>"Las virgenes suicidas", :author=>"Jeffrey Eugenides")
Book.create(:title =>"La memoria de las piedras", :author=>"Carol Shields")
Book.create(:title =>"Un buen partido", :author=>"Vikram Seth")
Book.create(:title =>"Tic-tac", :author=>"Suso de Toro")
Book.create(:title =>"Del amor", :author=>"Alain de Botton")
Book.create(:title =>"Gemelas", :author=>"Tessa de Loo")
Book.create(:title =>"Looking for a Possible Dance", :author=>"A.L. Kennedy")
Book.create(:title =>"Birdsong", :author=>"Sebastian Faulks")
Book.create(:title =>"Trainspotting", :author=>"Irvine Welsh")
Book.create(:title =>"Atando cabos", :author=>"E. Annie Proulx")
Book.create(:title =>"Cekani na tmu, cekani na svetlo", :author=>"Ivan Klima")
Book.create(:title =>"La escala de los mapas", :author=>"Belen Gopegui")
Book.create(:title =>"Dissapearance", :author=>"David Dabydeen")
Book.create(:title =>"Rio profundo", :author=>"Shusaku Endo")
Book.create(:title =>"Gracias por la propina", :author=>"Ferran Torrent")
Book.create(:title =>"La mandolina del capitan Corelli", :author=>"Louis de Bernieres")
Book.create(:title =>"How Late it Was, How Late", :author=>"James Kelman")
Book.create(:title =>"Sestra", :author=>"Jachym Topol")
Book.create(:title =>"Sostiene Pereira", :author=>"Antonio Tabucchi")
Book.create(:title =>"Cronica del pajaro que da cuerda al mundo", :author=>"Haruki Murakami")
Book.create(:title =>"La Virgen de los Sicarios", :author=>"Fernando Vallejo")
Book.create(:title =>"Las ultimas sombras", :author=>"Anjel Lertxundi")
Book.create(:title =>"Ampliacion del campo de batalla", :author=>"Michel Houellebecq")
Book.create(:title =>"El amor molesto", :author=>"Elena Ferrante")
Book.create(:title =>"Tonto, muerto, bastardo e invisible", :author=>"Juan Jose Millas")
Book.create(:title =>"The End of the Story", :author=>"Lydia Davis")
Book.create(:title =>"Love's Work", :author=>"Gillian Rose")
Book.create(:title =>"Un perfecto equilibrio", :author=>"Rohinton Mistry")
Book.create(:title =>"El lector", :author=>"Bernard Schlink")
Book.create(:title =>"Santa Evita", :author=>"Tomas Eloy Martinez")
Book.create(:title =>"Los pasos incontables", :author=>"Ramon Saizarbitoria")
Book.create(:title =>"Los inconsolables", :author=>"Kazuo Ishiguro")
Book.create(:title =>"Alias Grace", :author=>"Margaret Atwood")
Book.create(:title =>"El menique de Buda", :author=>"Victor Pelevin")
Book.create(:title =>"La broma infinita", :author=>"David Foster Wallace")
Book.create(:title =>"Seda", :author=>"Alessandro Baricco")
Book.create(:title =>"Ghost Road", :author=>"Pat Barker")
Book.create(:title =>"Piezas fugitivas", :author=>"Anne Michaels")
Book.create(:title =>"La locura de Foucault", :author=>"Patricia Dunker")
Book.create(:title =>"Una comedia ligera", :author=>"Eduardo Mendoza")
Book.create(:title =>"Carreteras secundarias", :author=>"Ignacio Martinez de Pison")
Book.create(:title =>"Fuegos con limon", :author=>"Fernando Aramburu")
Book.create(:title =>"El Dios de las pequenas cosas", :author=>"Arundhati Roy")
Book.create(:title =>"Margot en de Engelen", :author=>"Kristien Hemmerechts")
Book.create(:title =>"Plenilunio", :author=>"Antonio Munoz Molina")
Book.create(:title =>"Plata quemada", :author=>"Ricardo Piglia")
Book.create(:title =>"Jack Maggs", :author=>"Peter Carey")
Book.create(:title =>"Submundo", :author=>"Don DeLillo")
Book.create(:title =>"Bella en las tinieblas", :author=>"Manuel de Lope")
Book.create(:title =>"Kurosufaia (Crossfire)", :author=>"Miyabe Miyuki")
Book.create(:title =>"La biblia envenenada", :author=>"Barbara Kingsolver")
Book.create(:title =>"Veronika decide morir", :author=>"Paulo Coelho")
Book.create(:title =>"Las horas", :author=>"Michael Cunningham")
Book.create(:title =>"El dia de todas las almas", :author=>"Cees Nooteboom")
Book.create(:title =>"Rompenubes", :author=>"Russell Banks")
Book.create(:title =>"El hereje", :author=>"Miguel Delibes")
Book.create(:title =>"Las particulas elementales", :author=>"Michel Houellebecq")
Book.create(:title =>"The talk of the town", :author=>"Ardal O'Hanlon")
Book.create(:title =>"Trilogia sucia de La Habana", :author=>"Pedro Juan Gutierrez")
Book.create(:title =>"Los detectives salvajes", :author=>"Roberto Bolano")
Book.create(:title =>"Desgracia", :author=>"J.M. Coetzee")
Book.create(:title =>"Como si yo no estuviera", :author=>"Slavenka Drakulic")
Book.create(:title =>"Los romanticos", :author=>"Pankaj Mishra")
Book.create(:title =>"En busca de Klingsor", :author=>"Jorge Volpi")
Book.create(:title =>"El museo de la rendicion incondicional", :author=>"Dubravka Ugresic")
Book.create(:title =>"Estupor y temblores", :author=>"Amelie Nothomb")
Book.create(:title =>"House of Leaves", :author=>"Mark Z. Danielewski")
Book.create(:title =>"Blonde", :author=>"Joyce Carol Oates")
Book.create(:title =>"Bartleby y compania", :author=>"Enrique Vila-Matas")
Book.create(:title =>"Small Remedies", :author=>"Shashi Deshpande")
Book.create(:title =>"Piiririik", :author=>"Tonu Onnepalu")
Book.create(:title =>"Armonia celestial", :author=>"Peter Esterhazy")
Book.create(:title =>"La mancha humana", :author=>"Philip Roth")
Book.create(:title =>"Dientes blancos", :author=>"Zadie Smith")
Book.create(:title =>"Bajo la piel", :author=>"Michel Faber")
Book.create(:title =>"The Heart of Redness", :author=>"Zakes Mda")
Book.create(:title =>"Frias flores de marzo", :author=>"Ismail Kadare")
Book.create(:title =>"La ingorancia", :author=>"Milan Kundera")
Book.create(:title =>"An Obedient Father", :author=>"Akhil Sharma")
Book.create(:title =>"La Fiesta del Chivo", :author=>"Mario Vargas Llosa")
Book.create(:title =>"Asfixia", :author=>"Chuck Palahniuk")
Book.create(:title =>"Soldados de Salamina", :author=>"Javier Cercas")
Book.create(:title =>"At Swim, Two Boys", :author=>"Jamie O'Neill")
Book.create(:title =>"No te muevas", :author=>"Margaret Mazzantini")
Book.create(:title =>"Expiacion", :author=>"Ian McEwan")
Book.create(:title =>"Austerlitz", :author=>"W.G. Sebald")
Book.create(:title =>"Welcome to Our Hillbrow", :author=>"Phaswane Mpe")
Book.create(:title =>"Vida de Pi", :author=>"Yann Martel")
Book.create(:title =>"Las correcciones", :author=>"Jonathan Franzen")
Book.create(:title =>"Plataforma", :author=>"Michel Houellebecq")
Book.create(:title =>"El hombre de ninguna parte", :author=>"Aleksandar Hemon")
Book.create(:title =>"Los aires dificiles", :author=>"Almudena Grandes")
Book.create(:title =>"Imposturas", :author=>"John Banville")
Book.create(:title =>"Todo esta iluminado", :author=>"Jonathan Safran Foer")
Book.create(:title =>"Kafka en la orilla", :author=>"Haruki Murakami")
Book.create(:title =>"La sombra del viento", :author=>"Carlos Ruiz Zafon")
Book.create(:title =>"El primer amor de Casanova", :author=>"Arthur Japin")
Book.create(:title =>"Erec y Enide", :author=>"Manuel Vazquez Montalban")
Book.create(:title =>"Eilande", :author=>"Dan Sleigh")
Book.create(:title =>"The Namesake", :author=>"Jhumpa Lahiri")
Book.create(:title =>"El curioso incidente del perro a medianoche", :author=>"Mark Haddon")
Book.create(:title =>"Pasardhesi", :author=>"Ismail Kadare")
Book.create(:title =>"La dama numero trece", :author=>"Jose Carlos Somoza")
Book.create(:title =>"Todo cuanto ame", :author=>"Siri Hustvedt")
Book.create(:title =>"Blanco sobre negro", :author=>"Ruben Gallego")
Book.create(:title =>"Tu rostro manana", :author=>"Javier Marias")
Book.create(:title =>"Drop City", :author=>"T. Coraghessan Boyle")
Book.create(:title =>"El atlas de las nubes", :author=>"David Mitchell")
Book.create(:title =>"El testigo", :author=>"Juan Villoro")
Book.create(:title =>"2666", :author=>"Roberto Bolano")
Book.create(:title =>"Boken om Blanche och Marie", :author=>"Olov Enquist")
Book.create(:title =>"El maestro. Retrato del novelista adulto", :author=>"Colm Toibin")
Book.create(:title =>"La conjura contra America", :author=>"Philip Roth")
Book.create(:title =>"Al morir Don Quijote", :author=>"Andres Trapiello")
Book.create(:title =>"La Biblia de barro", :author=>"Julia Navarro")
Book.create(:title =>"Sabado", :author=>"Ian McEwan")
Book.create(:title =>"Die Vermessung der Welt", :author=>"Daniel Kehlmann")
